#pragma once

enum class MATERIAL
{
	NORMALS,
	MRAO,
	ORM,
	RMA,
	MRM,
	METAL,
	ROUGHNESS,
	EMISSIVE,
};


enum class ATTACK_TAG {
	ATK_PLAYER_NORMAL,
	ATK_PLAYER_HEAVY,
	ATK_PLAYER_FINALSLASH,
	ATK_PLAYER_MUSTANG,
	ATK_PLAYER_LASTCOMBO,
	ATK_PLAYER_BLOW,
	ATK_PLAYER_GRAB,
	
	ATK_MONSTER_NORMAL,
	ATK_MONSTER_BODYATTACK,
	ATK_MONSTER_INHALE,
	ATK_MONSTER_DOWN,
	ATK_MONSTER_BLOW,
};

enum class TRAVIS_TYPES {
	TRAVIS_BATTLE_GROUND,
	TRAVIS_BATTLE_GROUND_ARMOR,
	TRAVIS_BATTLE_SPACE,
	TRAVIS_WORLD,
	SMASHBROS_TRAVIS,

	TYPE_END
};

enum ABILITY_TYPE
{
	BULLETATTACK,
	SHOTSPEED,
	SHOT_INTERVAL,
	HORIZONTAL_SPEED_UP,
	VERTICAL_SPEED_UP,
	HEALING,
	ADD_HP,
	ABILITY_TYPE_END
};

enum CHEST_REWARD_TYPE
{
	ADD_DOG,
	ADD_DRAGON,
	ADD_DOG_ATTACK,
	ADD_DRAGON_ATTACK,
	REDUCE_DOG_ATTACK_INTERVAL,
	REDUCE_DRAGON_ATTACK_INTERVAL,
	CHEST_REWARD_TYPE_END,
};

enum REWARD_TYPE
{
	UPGRADE_BULLET,
	UPGRADE_BREATH,
	SUPERMODE,
	REWARD_TYPE_END,
};


enum ANIM_SHADERPASS
{
	PASS_DEFAULT,
	PASS_DISSOLVE,
	PASS_CASCADE,
	PASS_SHADOWDEPTH,
	PASS_MOTION_TRAIL,
	PASS_DISTORTION,
	PASS_FORWARD_PBR,
	PASS_DEFAULT_WITH_STENCIL,
	PASS_ALPHABLEND,
};

enum GAME_FLOW {
	FLOW_Jean_dissapeared,
	FLOW_Battle_Motel_Front_Cleared,
	FLOW_First_PhoneCall_End,
	FLOW_Quest_ToiletMinigame_Cleared,
	FLOW_Quest_TrashCollector_Cleared,
	FLOW_Quest_BattleIsland_Cleared,
	FLOW_Silvia_Conversation_End,
	FLOW_Boss_Blackhole_Cleared,
	FLOW_Boss_SonicJuice_Cleared,
	FLOW_Boss_Damon_Opened,
	FLOW_Boss_Damon_Cleard,

	FLOW_END
};